apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-security-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: platform
  source:
    repoURL: git@github.com:Miracle-1331/extreme-k8s-lab.git
    targetRevision: main
    path: gitops/security/audit
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
