apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-manifests-dev
  namespace: argocd
spec:
  project: platform

  source:
    repoURL: git@github.com:Miracle-1331/extreme-k8s-lab.git
    targetRevision: main
    path: gitops/resources
    directory:
      recurse: true
      exclude: "{cloudflared/**}"

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
