driver:
  kind: modern_ebpf

tty: true

falco:
  json_output: true
  log_level: info
  priority: warning

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
