# ansible/playbooks/04-cni.yaml

- name: Install Cilium CNI
  hosts: control_plane
  become: true

  tasks:
    - name: Install Cilium CLI
      ansible.builtin.shell: |
        set -euo pipefail

        CILIUM_CLI_VERSION="$(curl -fsSL https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)"
        CLI_ARCH="arm64"

        curl -L --fail --remote-name-all \
          "https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz"

        tar xzvfC "cilium-linux-${CLI_ARCH}.tar.gz" /usr/local/bin

        rm -f "cilium-linux-${CLI_ARCH}.tar.gz"
      args:
        executable: /bin/bash
        creates: /usr/local/bin/cilium

    - name: Check if Cilium is already installed
      ansible.builtin.command: kubectl --kubeconfig=/etc/kubernetes/admin.conf get daemonset cilium -n kube-system
      register: cilium_ds
      failed_when: false
      changed_when: false

    - name: Install Cilium
      ansible.builtin.command: cilium install
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      when: cilium_ds.rc != 0

    - name: Wait for Cilium
      ansible.builtin.command: cilium status --wait
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
