apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-infra-dev
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: cert-manager
            repoURL: https://charts.jetstack.io
            chart: cert-manager
            targetRevision: "v1.20.2"
            namespace: cert-manager
            releaseName: cert-manager
            valuesPath: gitops/infra/cert-manager/dev.yaml
            createNamespace: "true"

          # - name: vault
          #   repoURL: https://helm.releases.hashicorp.com
          #   chart: vault
          #   targetRevision: "0.32.0"
          #   namespace: vault
          #   releaseName: vault
          #   valuesPath: gitops/infra/vault/dev.yaml
          #   createNamespace: "false"

          # - name: observability-grafana
          #   repoURL: https://grafana.github.io/helm-charts
          #   chart: grafana
          #   targetRevision: "10.2.0"
          #   namespace: observability
          #   releaseName: grafana
          #   valuesPath: gitops/infra/grafana/dev.yaml
          #   createNamespace: "false"

          # - name: observability-loki
          #   repoURL: https://grafana.github.io/helm-charts
          #   chart: loki
          #   targetRevision: "6.46.0"
          #   namespace: observability
          #   releaseName: loki
          #   valuesPath: gitops/infra/loki/dev.yaml
          #   createNamespace: "false"

          # - name: observability-alloy
          #   repoURL: https://grafana.github.io/helm-charts
          #   chart: alloy
          #   targetRevision: "1.4.0"
          #   namespace: observability
          #   releaseName: alloy
          #   valuesPath: gitops/infra/alloy/dev.yaml
          #   createNamespace: "false"

          # - name: observability-mimir
          #   repoURL: https://grafana.github.io/helm-charts
          #   chart: mimir-distributed
          #   targetRevision: "6.0.4"
          #   namespace: observability
          #   releaseName: mimir
          #   valuesPath: gitops/infra/mimir/dev.yaml
          #   createNamespace: "false"

          # - name: observability-tempo
          #   repoURL: https://grafana.github.io/helm-charts
          #   chart: tempo
          #   targetRevision: "1.24.3"
          #   namespace: observability
          #   releaseName: tempo
          #   valuesPath: gitops/infra/tempo/dev.yaml
          #   createNamespace: "false"
  template:
    metadata:
      name: "{{.name}}"
      namespace: argocd
    spec:
      project: platform

      sources:
        - repoURL: "{{.repoURL}}"
          chart: "{{.chart}}"
          targetRevision: "{{.targetRevision}}"
          helm:
            releaseName: "{{.releaseName}}"
            valueFiles:
              - $values/{{.valuesPath}}

        - repoURL: git@github.com:Miracle-1331/extreme-k8s-lab.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace={{.createNamespace}}
