apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    gateway-access: public
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: kong
---
apiVersion: v1
kind: Namespace
metadata:
  name: public
  labels:
    gateway-access: public
